"use client";

import React from "react";
import { motion } from "framer-motion";
import { Mail } from "lucide-react";
import SectionLabel from "@/components/shared/SectionLabel";

const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 18 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-60px" },
  transition: { delay, duration: 0.5, ease: [0.22, 1, 0.36, 1] as const },
});

type Item = { label: string; description: string };
type Section = { title: string; content?: string; intro?: string; extra?: string; bullets?: string[]; items?: Item[] };

const SECTIONS: Section[] = [
  {
    title: "Use of Our Services",
    content: "Our services are intended for healthcare organizations and professionals seeking clinical documentation and revenue cycle automation. You agree to use our services only for lawful purposes and in compliance with all applicable regulations.",
    intro: "You may not:",
    bullets: [
      "Misuse, disrupt, or interfere with the functionality of our website or AI platform.",
      "Attempt unauthorized access to our systems, data, infrastructure, or revenue cycle database.",
      "Use our services for fraudulent purposes or in a manner designed to circumvent applicable healthcare billing regulations.",
    ],
  },
  {
    title: "Clinical and Professional Responsibility",
    intro: "NuScript Systems provides AI-powered documentation and revenue cycle automation through the Zera platform. The following responsibilities remain with the User at all times:",
    items: [
      { label: "No Medical Advice", description: "Nothing in our services constitutes medical advice, diagnosis, or treatment. The Zera platform generates clinical documentation and coding suggestions to support — not replace — clinical judgment." },
      { label: "Provider Responsibility", description: "Clinicians maintain sole professional responsibility for the accuracy of all clinical notes generated by the Zera platform. All medical decisions, patient care determinations, and final billing submissions remain the responsibility of the licensed provider." },
      { label: "Verification of AI Output", description: "User acknowledges that the Zera platform utilizes machine learning models whose outputs may require correction. You agree to review all AI-generated content, documentation, and coding suggestions for accuracy before finalizing records or submitting claims." },
    ],
  },
  {
    title: "Intellectual Property & Proprietary Rights",
    content: "All content on this website — including text, logos, graphics, the Zera brand, and the underlying AI models, algorithms, and associated intellectual property powering the Zera platform — is the exclusive property of NuScript Systems, Inc. and is protected by applicable intellectual property laws.",
    items: [
      { label: "Restrictions", description: "You are expressly prohibited from attempting to reverse engineer, decompile, disassemble, or otherwise extract the source code, model weights, or proprietary logic of any Zera product or service." },
      { label: "Third-Party Marks", description: "Product and platform names referenced on this site (including Epic, athenahealth, and Oracle Cerner) are trademarks of their respective owners. Their use is solely for identification and interoperability description purposes and does not imply endorsement, partnership, or affiliation." },
    ],
  },
  {
    title: "Interoperability & Third-Party Integrations",
    content: "Our services rely on integrations with third-party Electronic Health Record (EHR) systems and interoperability middleware. NuScript Systems is not liable for service interruptions, data synchronization errors, or platform downtime caused by third-party systems outside our control. We will make reasonable efforts to notify users of known integration issues affecting service availability.",
  },
  {
    title: "Disclaimers",
    intro: "Our services are provided \"as is\" and \"as available\" without warranties of any kind, express or implied. We do not warrant that:",
    bullets: [
      "The website or AI platform will be error-free, uninterrupted, or free of security vulnerabilities.",
      "The services will guarantee specific financial outcomes, reimbursement rates, or claim approval results.",
      "AI-generated documentation or coding suggestions will be complete or accurate without human review and oversight.",
    ],
  },
  {
    title: "Limitation of Liability",
    content: "To the fullest extent permitted by applicable law, NuScript Systems shall not be liable for any indirect, incidental, special, or consequential damages — including loss of revenue, data, or business opportunity — arising from your use of, or inability to use, the platform.",
    extra: "Our total aggregate liability for any claim arising out of or related to these Terms or our services shall not exceed the total fees paid by you in the six (6) months prior to the event giving rise to the claim.",
  },
  {
    title: "Governing Law & Jurisdiction",
    content: "These Terms are governed by and construed in accordance with the laws of the State of Texas, without regard to its conflict of law provisions. Any disputes arising under or related to these Terms shall be resolved exclusively in the state or federal courts located in Texas, and you irrevocably consent to the personal jurisdiction of such courts.",
  },
  {
    title: "Modifications to These Terms",
    content: "We reserve the right to update or modify these Terms at any time. Material changes will be communicated by updating the \"Last Updated\" date at the top of this page. Your continued use of our services following any modification constitutes your acceptance of the revised Terms.",
  },
];

function BulletItem({ label, description }: { label?: string; description: string }) {
  return (
    <li className="flex gap-3 sm:gap-4">
      <div className="flex-shrink-0 w-5 h-5 rounded-md bg-primary/10 flex items-center justify-center mt-[3px]">
        <span aria-hidden="true" className="w-1.5 h-1.5 rounded-full bg-primary" />
      </div>
      <div className="flex-1">
        {label && <h3 className="text-base font-bold text-foreground mb-1">{label}</h3>}
        <p className="text-muted-foreground leading-relaxed">{description}</p>
      </div>
    </li>
  );
}

export default function TermsOfUse() {
  return (
    <>
      {/* Hero */}
      <section className="pt-32 pb-16 sm:pt-40 sm:pb-20 lg:pt-44 lg:pb-24">
        <div className="max-w-[1180px] mx-auto px-4 md:px-[1.5938rem] lg:px-[1.75rem]">
          <motion.div {...fadeUp(0)}>
            <SectionLabel>Legal</SectionLabel>
          </motion.div>
          <motion.h1 {...fadeUp(0.08)} className="text-4xl sm:text-5xl lg:text-6xl font-bold text-foreground mt-4 leading-tight max-w-4xl">
            Terms of Use
          </motion.h1>
          <motion.p {...fadeUp(0.16)} className="text-lg text-muted-foreground mt-6">
            Effective Date: July 5, 2026
          </motion.p>
        </div>
      </section>

      {/* Body */}
      <section className="bg-muted/30 py-20 sm:py-24 lg:py-28">
        <div className="mx-auto max-w-4xl px-4 md:px-[1.5938rem] lg:px-[1.75rem]">
          <motion.div {...fadeUp(0)} className="mb-14">
            <h2 className="text-2xl font-bold text-foreground mb-4">Introduction</h2>
            <p className="text-lg text-muted-foreground leading-relaxed">
              Please read these Terms of Use (&ldquo;Terms&rdquo;) carefully before using the website and services operated by NuScript Systems, Inc. (&ldquo;NuScript Systems&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;). By accessing or using our website or services, you agree to be bound by these Terms. If you do not agree, you may not use our services.
            </p>
          </motion.div>

          <div className="space-y-14">
            {SECTIONS.map((section, idx) => (
              <motion.div key={section.title} {...fadeUp(idx * 0.04)}>
                <h2 className="text-2xl font-bold text-foreground mb-4">{idx + 1}. {section.title}</h2>
                {section.content && <p className="text-lg text-muted-foreground leading-relaxed mb-5">{section.content}</p>}
                {section.extra && <p className="text-lg text-muted-foreground leading-relaxed mb-5">{section.extra}</p>}
                {section.intro && <p className="text-lg text-muted-foreground leading-relaxed mb-5">{section.intro}</p>}
                {section.bullets && (
                  <ul className="space-y-4">
                    {section.bullets.map((line) => (
                      <BulletItem key={line} description={line} />
                    ))}
                  </ul>
                )}
                {section.items && (
                  <ul className="space-y-4">
                    {section.items.map((item) => (
                      <BulletItem key={item.label} label={item.label} description={item.description} />
                    ))}
                  </ul>
                )}
              </motion.div>
            ))}
          </div>

          <motion.div {...fadeUp(0)} className="mt-16 pt-12 border-t border-border">
            <h2 className="text-2xl font-bold text-foreground mb-6">9. Contact</h2>
            <div className="rounded-2xl border border-border bg-white p-6 sm:p-8">
              <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                For questions or concerns regarding these Terms, please contact:
              </p>
              <div className="space-y-2 mb-6">
                <p className="text-foreground font-semibold">NuScript Systems, Inc.</p>
                <p className="text-muted-foreground">Attn: Legal Team</p>
              </div>
              <div className="flex items-center gap-3 pt-4 border-t border-border">
                <Mail className="w-4 h-4 text-primary flex-shrink-0" aria-hidden="true" />
                <a href="mailto:hello@zera.health" className="text-primary font-semibold hover:underline">hello@zera.health</a>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </>
  );
}
